x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

x-service-defaults: &service-defaults
  <<: *logging
  stop_grace_period: 1s
  entrypoint:
    - "/project/entrypoint.sh"
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-api-service-defaults: &api-service-defaults
  <<: *service-defaults
  healthcheck:
    test: ["CMD", "/bin/bash", "/project/healthcheck.sh"]
    interval: 360s
    timeout: 1s
    retries: 1
    start_period: 3s
  restart: always


services:
  db:
    image: postgres:16.4-bookworm
    restart: always
    env_file:
      - ${DB_ENV_FILE}
    volumes:
      - .docker_volumes/postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    <<: *logging

  private_api:
    build: ./private_api
    volumes:
      - "./private_api:/project"
      - "./shared:/libs/shared"
    env_file:
      - ${PRIVATE_API_ENV_FILE}
    depends_on:
      - db
    ports:
      - ${PRIVATE_API_PORT}:8000
    <<: *api-service-defaults
