x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

x-service-defaults: &service-defaults
  <<: *logging
  stop_grace_period: 1s
  entrypoint:
    - "/project/entrypoint.sh"
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  db:
    image: postgres:16.4-bookworm
    restart: always
    env_file:
      - ${DB_ENV_FILE}
    volumes:
      - .docker_volumes/postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    <<: *logging

  internal_api:
    build: ./internal_api
    volumes:
      - "./internal_api:/project"
      - "./shared:/libs/shared"
    env_file:
      - ${INTERNAL_API_ENV_FILE}
    depends_on:
      - db
    ports:
      - ${INTERNAL_API_PORT}:8000
    <<: *service-defaults


networks:
  default:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true
