x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"


x-service-defaults: &service-defaults
  stop_grace_period: 1s
  entrypoint:
    - "/project/entrypoint.sh"


services:
  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:8000
    depends_on:
      api:
        condition: service_healthy
    <<: *logging

  api:
    build: ./api
    restart: always
    volumes:
      - "./api:/project"
    env_file:
      - ${API_ENV_FILE}
    ports:
      - ${API_PORT}:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netcat -z localhost 8000"]
      start_period: 10s
    <<: *service-defaults

  db:
    image: postgres:16.4-bookworm
    restart: always
    env_file:
      - ${DB_ENV_FILE}
    volumes:
      - .docker_volumes/postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432"]
      start_period: 10s
    <<: *logging