"""Test 2

Revision ID: 35bfc092d988
Revises: e2db08b75dc4
Create Date: 2025-03-09 21:08:16.023265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35bfc092d988'
down_revision: Union[str, None] = 'e2db08b75dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_index', 'users', ['email'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_index', table_name='users', postgresql_using='hash')
    # ### end Alembic commands ###
