"""Remove UserRole

Revision ID: da1039f932b9
Revises: 35bfc092d988
Create Date: 2025-03-10 12:36:13.130256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da1039f932b9'
down_revision: Union[str, None] = '35bfc092d988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'TEACHER', 'STUDENT', name='userrole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
