"""Update user model, change email -> username

Revision ID: a6ff619359a5
Revises: 278438eb01da
Create Date: 2025-03-11 22:48:03.748611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ff619359a5'
down_revision: Union[str, None] = '278438eb01da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_index('email_index', table_name='users', postgresql_using='hash')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('username_index', 'users', ['username'], unique=False, postgresql_using='hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('username_index', table_name='users', postgresql_using='hash')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('email_index', 'users', ['email'], unique=False, postgresql_using='hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
