from .user import UserRepo as UserRepo
from .discipline import DisciplineRepo as DisciplineRepo
from .discipline_group import DisciplineGroupRepo as DisciplineGroupRepo
from .discipline_teacher import DisciplineTeacherRepo as DisciplineTeacherRepo
from .mark import MarkRepo as MarkRepo
from .group import GroupRepo as GroupRepo
from .track import TrackRepo as TrackRepo
from .unit import UnitRepo as UnitRepo
from .student import StudentRepo as StudentRepo
from .teacher import TeacherRepo as TeacherRepo
